-- ==============================================================================
-- ERMAY MUHASEBE - SUPABASE EKSIK TABLOLAR VE ŞEMA SENKRONIZASYON SCRIPTI
-- ==============================================================================
-- Bu betik, Masaüstü ve Mobil uygulamalar arasındaki senkronizasyonda eksik olan
-- tüm tabloları, identity yapılandırmalarını ve RLS politikalarını oluşturur.
-- ==============================================================================

-- 1. DETAY TABLOLARI IDENTITY DESTEGI (NULL ID HATASINI ÖNLEMEK ICIN)
DO $$
BEGIN
    -- fatura_detaylar tablosunda id kolonu identity değilse sequence ekle
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'fatura_detaylar' AND column_name = 'id') THEN
        ALTER TABLE public.fatura_detaylar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL; -- Zaten identity ise hata verme
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'siparis_detaylar' AND column_name = 'id') THEN
        ALTER TABLE public.siparis_detaylar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_name = 'teklif_detaylar' AND column_name = 'id') THEN
        ALTER TABLE public.teklif_detaylar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
EXCEPTION WHEN OTHERS THEN
    NULL;
END $$;

-- 2. ÇEKLER TABLOSU
CREATE TABLE IF NOT EXISTS public.cekler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cek_no TEXT,
    vade_tarihi TIMESTAMPTZ,
    tutar NUMERIC DEFAULT 0,
    kesideci TEXT,
    banka TEXT,
    sube TEXT,
    hesap_no TEXT,
    durum TEXT DEFAULT 'Portföyde',
    cari_id BIGINT,
    cari_unvan TEXT,
    aciklama TEXT,
    mali_yil INT DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    uuid TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.cekler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cekler_all_policy" ON public.cekler;
CREATE POLICY "cekler_all_policy" ON public.cekler FOR ALL USING (true) WITH CHECK (true);

-- 3. SENETLER TABLOSU
CREATE TABLE IF NOT EXISTS public.senetler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senet_no TEXT,
    vade_tarihi TIMESTAMPTZ,
    tutar NUMERIC DEFAULT 0,
    borclu TEXT,
    durum TEXT DEFAULT 'Portföyde',
    cari_id BIGINT,
    cari_unvan TEXT,
    aciklama TEXT,
    mali_yil INT DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    uuid TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.senetler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "senetler_all_policy" ON public.senetler FOR ALL USING (true) WITH CHECK (true);

-- 4. KREDİ KARTI İŞLEMLERİ
CREATE TABLE IF NOT EXISTS public.kredi_karti_islemler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    musteri_id BIGINT,
    musteri_unvan TEXT,
    tarih TIMESTAMPTZ DEFAULT NOW(),
    tutar NUMERIC DEFAULT 0,
    banka TEXT,
    kart_no TEXT,
    onay_kodu TEXT,
    durum TEXT,
    aciklama TEXT,
    islem_turu TEXT,
    slip_dosya_yolu TEXT,
    yonlendirilen_cari_id BIGINT,
    yonlendirilen_cari_unvan TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.kredi_karti_islemler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "kredi_karti_islemler_all_policy" ON public.kredi_karti_islemler;
CREATE POLICY "kredi_karti_islemler_all_policy" ON public.kredi_karti_islemler FOR ALL USING (true) WITH CHECK (true);

-- 5. EFT / HAVALE İŞLEMLERİ
CREATE TABLE IF NOT EXISTS public.eft_islemler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    musteri_id BIGINT,
    musteri_unvan TEXT,
    tarih TIMESTAMPTZ DEFAULT NOW(),
    tutar NUMERIC DEFAULT 0,
    banka TEXT,
    banka_id BIGINT,
    hesap_no TEXT,
    dekont_no TEXT,
    durum TEXT,
    aciklama TEXT,
    islem_turu TEXT,
    dekont_path TEXT,
    yonlendirilen_cari_id BIGINT,
    yonlendirilen_cari_unvan TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.eft_islemler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "eft_islemler_all_policy" ON public.eft_islemler;
CREATE POLICY "eft_islemler_all_policy" ON public.eft_islemler FOR ALL USING (true) WITH CHECK (true);

-- 6. GÖREVLER
CREATE TABLE IF NOT EXISTS public.gorevler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    baslik TEXT,
    aciklama TEXT,
    durum TEXT DEFAULT 'Bekliyor',
    oncelik TEXT DEFAULT 'Normal',
    tarih TIMESTAMPTZ DEFAULT NOW(),
    bitis_tarihi TIMESTAMPTZ,
    atanan_kisi TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.gorevler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "gorevler_all_policy" ON public.gorevler;
CREATE POLICY "gorevler_all_policy" ON public.gorevler FOR ALL USING (true) WITH CHECK (true);

-- 7. PERSONELLER
CREATE TABLE IF NOT EXISTS public.personeller (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_soyad TEXT,
    tc_no TEXT,
    telefon TEXT,
    eposta TEXT,
    departman TEXT,
    gorev TEXT,
    maas NUMERIC DEFAULT 0,
    ise_giris_tarihi TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.personeller ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "personeller_all_policy" ON public.personeller FOR ALL USING (true) WITH CHECK (true);

-- 8. SATIŞ HEDEFLERİ
CREATE TABLE IF NOT EXISTS public.satis_hedefleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yil INT,
    ay INT,
    hedef_tutar NUMERIC DEFAULT 0,
    gerceklesen_tutar NUMERIC DEFAULT 0,
    aciklama TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.satis_hedefleri ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "satis_hedefleri_all_policy" ON public.satis_hedefleri;
CREATE POLICY "satis_hedefleri_all_policy" ON public.satis_hedefleri FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.haftalik_satis_hedefleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yil INT,
    hafta INT,
    hedef_tutar NUMERIC DEFAULT 0,
    gerceklesen_tutar NUMERIC DEFAULT 0,
    aciklama TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.haftalik_satis_hedefleri ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "haftalik_satis_hedefleri_all_policy" ON public.haftalik_satis_hedefleri;
CREATE POLICY "haftalik_satis_hedefleri_all_policy" ON public.haftalik_satis_hedefleri FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.yillik_satis_hedefleri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yil INT,
    hedef_tutar NUMERIC DEFAULT 0,
    gerceklesen_tutar NUMERIC DEFAULT 0,
    aciklama TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.yillik_satis_hedefleri ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "yillik_satis_hedefleri_all_policy" ON public.yillik_satis_hedefleri FOR ALL USING (true) WITH CHECK (true);

-- 9. PORTFÖY KARTLAR (KASA VE BANKA DETAYLARI)
CREATE TABLE IF NOT EXISTS public.portfoy_kartlar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kart_turu TEXT,
    kart_adi TEXT,
    kart_no TEXT,
    banka TEXT,
    bakiye NUMERIC DEFAULT 0,
    limit_tutar NUMERIC DEFAULT 0,
    kesim_gunu INT,
    son_odeme_gunu INT,
    aciklama TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.portfoy_kartlar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "portfoy_kartlar_all_policy" ON public.portfoy_kartlar;
CREATE POLICY "portfoy_kartlar_all_policy" ON public.portfoy_kartlar FOR ALL USING (true) WITH CHECK (true);

-- 10. STOK SAYIM
CREATE TABLE IF NOT EXISTS public.stok_sayim_fisileri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fis_no TEXT,
    tarih TIMESTAMPTZ DEFAULT NOW(),
    aciklama TEXT,
    durum TEXT DEFAULT 'Taslak',
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.stok_sayim_fisileri ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stok_sayim_fisileri_all_policy" ON public.stok_sayim_fisileri;
CREATE POLICY "stok_sayim_fisileri_all_policy" ON public.stok_sayim_fisileri FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.stok_sayim_detaylari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sayim_id BIGINT,
    stok_id BIGINT,
    stok_kodu TEXT,
    stok_adi TEXT,
    mevcut_miktar NUMERIC DEFAULT 0,
    sayilan_miktar NUMERIC DEFAULT 0,
    fark_miktar NUMERIC DEFAULT 0,
    birim TEXT DEFAULT 'Adet'
);
ALTER TABLE public.stok_sayim_detaylari ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "stok_sayim_detaylari_all_policy" ON public.stok_sayim_detaylari;
CREATE POLICY "stok_sayim_detaylari_all_policy" ON public.stok_sayim_detaylari FOR ALL USING (true) WITH CHECK (true);

-- 11. DÖVİZ KURLARI
CREATE TABLE IF NOT EXISTS public.doviz_kurlari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod TEXT,
    ad TEXT,
    alis NUMERIC DEFAULT 0,
    satis NUMERIC DEFAULT 0,
    efektif_alis NUMERIC DEFAULT 0,
    efektif_satis NUMERIC DEFAULT 0,
    tarih TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.doviz_kurlari ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "doviz_kurlari_all_policy" ON public.doviz_kurlari;
CREATE POLICY "doviz_kurlari_all_policy" ON public.doviz_kurlari FOR ALL USING (true) WITH CHECK (true);

-- 12. BELGE ARŞİV
CREATE TABLE IF NOT EXISTS public.belge_arsiv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    belge_turu TEXT,
    belge_no TEXT,
    ilgili_id BIGINT,
    dosya_adi TEXT,
    dosya_yolu TEXT,
    dosya_tipi TEXT,
    boyut BIGINT,
    yukleme_tarihi TIMESTAMPTZ DEFAULT NOW(),
    is_deleted BOOLEAN DEFAULT FALSE
);
ALTER TABLE public.belge_arsiv ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "belge_arsiv_all_policy" ON public.belge_arsiv;
CREATE POLICY "belge_arsiv_all_policy" ON public.belge_arsiv FOR ALL USING (true) WITH CHECK (true);

-- 13. MÜŞTERİ TAKİP KLASÖRLER VE DETAYLAR
CREATE TABLE IF NOT EXISTS public.musteri_takip_klasorler (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klasor_adi TEXT,
    cari_id BIGINT,
    aciklama TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.musteri_takip_klasorler ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "musteri_takip_klasorler_all_policy" ON public.musteri_takip_klasorler;
CREATE POLICY "musteri_takip_klasorler_all_policy" ON public.musteri_takip_klasorler FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.musteri_takip_detaylar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    klasor_id BIGINT,
    baslik TEXT,
    icerik TEXT,
    dosya_yolu TEXT,
    tarih TIMESTAMPTZ DEFAULT NOW(),
    is_deleted BOOLEAN DEFAULT FALSE
);
ALTER TABLE public.musteri_takip_detaylar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "musteri_takip_detaylar_all_policy" ON public.musteri_takip_detaylar;
CREATE POLICY "musteri_takip_detaylar_all_policy" ON public.musteri_takip_detaylar FOR ALL USING (true) WITH CHECK (true);

-- 14. MALİ YILLAR
CREATE TABLE IF NOT EXISTS public.mali_yillar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    yil INT UNIQUE,
    aciklama TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    is_closed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.mali_yillar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "mali_yillar_all_policy" ON public.mali_yillar;
CREATE POLICY "mali_yillar_all_policy" ON public.mali_yillar FOR ALL USING (true) WITH CHECK (true);

-- 15. MOBİL GELEN KUTUSU (INBOX)
CREATE TABLE IF NOT EXISTS public.mobil_gelen_kutusu (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    islem_turu TEXT NOT NULL,
    kaynak_cihaz TEXT,
    payload JSONB NOT NULL,
    durum TEXT NOT NULL DEFAULT 'Bekliyor',
    hata_mesaji TEXT,
    resmi_evrak_no TEXT,
    mali_yil INT NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    islenme_tarihi TIMESTAMPTZ
);
ALTER TABLE public.mobil_gelen_kutusu ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "mobil_gelen_kutusu_all_policy" ON public.mobil_gelen_kutusu;
CREATE POLICY "mobil_gelen_kutusu_all_policy" ON public.mobil_gelen_kutusu FOR ALL USING (true) WITH CHECK (true);

-- 16. GÜVENLİK VE KULLANICI YÖNETİMİ
CREATE TABLE IF NOT EXISTS public.security_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT,
    request_type TEXT,
    status TEXT DEFAULT 'Pending',
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.security_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "security_requests_all_policy" ON public.security_requests;
CREATE POLICY "security_requests_all_policy" ON public.security_requests FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public.user_security_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE,
    is_locked BOOLEAN DEFAULT FALSE,
    failed_attempts INT DEFAULT 0,
    last_login TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.user_security_states ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "user_security_states_all_policy" ON public.user_security_states;
CREATE POLICY "user_security_states_all_policy" ON public.user_security_states FOR ALL USING (true) WITH CHECK (true);
